### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by EPadronU**

### CODE REVIEW

**Comment by FineFindus** [comment]
I'm not quite sure what the goal of this pull request is, the manifest is already up to date with the latest released version and the current 45 runtime?

**Comment by EPadronU** [comment]
> I'm not quite sure what the goal of this pull request is, the manifest is already up to date with the latest released version and the current 45 runtime?

I'd like to make available the latest changes you have introduced. Like the tooltips for the color pallet, for example.

**Comment by EPadronU** [comment]
Bot build

**Comment by EPadronU** [comment]
bot, build

**Comment by FineFindus** [comment]
Thanks, but I think it would be better to have a beta upstream release first instead of building with a random git commit. Although I'm not sure if there have been enough changes to warrant it.
If you still want to use a version based on the latest git commit, you can also download the release artifact from the CI.

**Pull request closed without merging**
